### ISSUE TITLE
[メモ]Github内資料リスト(非質問)

### ISSUE THREAD

**Issue by LiuMing5489** [trex-group/Big-Data#11]
・各手順
https://github.com/trex-group/Big-Data/tree/master/01_Guide/environment/Manual

・Ubuntuインストール手順
https://github.com/trex-group/Big-Data/blob/master/01_Guide/environment/Manual/OS_Ubuntu_14.04.pdf

・Hadoopインストール手順（on Ubuntu）
https://github.com/trex-group/Big-Data/blob/master/01_Guide/environment/Manual/Hadoop_Ubuntu_14.04.pdf

・Vim常用命令
https://github.com/trex-group/Big-Data/blob/master/01_Guide/environment/Manual/Vim.pdf
随時追加...

**Comment by xenron** [comment]
well done

**Comment by LiuMing5489** [comment]
想用wiki来着，用法没弄明白，暂时先放这。
