### ISSUE TITLE
[メモ]常用Linux命令(非質問)

### ISSUE THREAD

**Issue by LiuMing5489** [trex-group/Big-Data#12]
・change ipaddress for ubuntu
http://shodai.hatenablog.com/entry/20130622/1371830832

・鍵交換方式によるssh接続（无密码登陆）
http://kazmax.zpp.jp/linux/lin_sshrsa.html

・etc/passwdと/etc/shadowの整合性が取れていない時の対処方法
$pwconv

随时更新

**Comment by lufengfeng** [comment]
好

**Comment by LiuMing5489** [comment]
仕事仕事ｗ
