### ISSUE TITLE
[メモ]准备入手mac本本的同学必看

### ISSUE THREAD

**Issue by LiuMing5489** [trex-group/Big-Data#14]
・大小
11，13，15，17 白菜萝卜各有所爱
因为可以外接显示器，考虑到便携性，推荐13

・键盘
建议入手英文键盘的。

・内存
mac air自己增设比较费事建议一步到位搞大一点（最少8g?）

・硬盘
之后可以自己增设，根据经济状况决定

**Comment by McKey1911** [comment]
1. 本本的话直接MacBook Pro（因为可以冒充得专业一点，笑）
2. MacBook最新款，带着一个touch bar，虽然是作为一个卖点，但是对于程序猿们来说好像也不是重点
3. 13英寸的内存8g，16g得买15英寸的了（官网看来的）
4. 8g内存，总感觉不够啊
5. 在ビックカメラ没有看到英文键盘版Pro，但是价格上比官网便宜一丢丢，还有10%的point
6. 日文键盘装VM的时候要选择合适的键盘模式。我选择了英文键盘模式，【~】输入不了，进home目录的时候老麻烦了！   ***手动添加注释：选择英文键盘模式实际上是日文键盘的时候是可以输入【～】的，请参看下面 @shendb 兄的comment***
7. 也是Mac新手。就这么多了。

**Comment by xenron** [comment]
外接设备的话，体验可能会好些
Monitor & HHBK & Mouse

**Comment by shendb** [comment]
~ 这个符号日文键盘是 [shift + （空格键左边的英数键）]

**Comment by McKey1911** [comment]
果然可以！谢谢！@shendb

**Comment by dadahu** [comment]
macbook air入手一台（没有勇气冒充专业人士，哈），
上了第二节课发现内存128G，太容易被吃掉啦，果然是bigData啊。
另外，看了各位的技术贴，有种跟不上思路的节奏啊！先在这打打酱油。；）

**Comment by LiuMing5489** [comment]
硬盘已经用了128G了？
有点多啊。是不是还下载别的了？哈哈
一起围观大神们。：）

**Comment by xenron** [comment]
我自己的macbook pro 975，硬盘也是128，还算够用吧
家里有nas的话，电脑上的硬盘倒也不需要很大。

@dadahu 有什么问题，想法，都可以和大家一起交流
开源的技术领域和现在日本的IT工作环境有很多不一样的地方。
大家慢慢适应脱离手顺，达到问题驱动解决方案的方式，技术水平可能会提高的更快。
当然，工作环境中还是按照客户的要求去做。
