### ISSUE TITLE
hadoop-Develop 的root密码

### ISSUE THREAD

**Issue by iameyama** [trex-group/Big-Data#26]

**Comment by iameyama** [comment]
hadoop-Develop 的root密码是都少啊？
![image](https://cloud.githubusercontent.com/assets/19360413/23958881/e0ee1560-09e6-11e7-8ecb-f9c2f49fb707.png)

好像不是ubuntu

**Comment by LiuMing5489** [comment]
大数据讲师-徐  21:42:39
passwd root
大数据讲师-徐  21:42:42
重新设置一下
大数据讲师-徐  21:44:01
桌面版没设置root用户，貌似开发的时候用不到。。。就没设置。。。

**Comment by xenron** [comment]
汗。。。

**Comment by LiuMing5489** [comment]
哈哈 当了一下搬运工
