### ISSUE TITLE
通过IDE远程执行WordCount时不显示执行log

### ISSUE THREAD

**Issue by jplijplijpli** [trex-group/Big-Data#35]
第二次的作业运行Hadoop-Remote。。。Hadoop-Server上面可以确认output文件的生成。但是IDE的Console上面没有显示task的执行log。请问通过IDE执行就是这样的吗？有没有workaround？

IDE的console上面无执行log：
![image](https://cloud.githubusercontent.com/assets/26088047/24331506/b2ad8e78-1270-11e7-8595-1cb594f45dbd.png)

可确认已经执行成功：
![image](https://cloud.githubusercontent.com/assets/26088047/24331510/bfd91068-1270-11e7-8c31-a7bafdc6b867.png)

**Comment by LiuMing5489** [comment]
输出的。自己放一份log4j的配置文件就ok了.(eclipse default是 classes/目录)

**Comment by xenron** [comment]
good
可以熟悉一下log4j，配置起来也挺复杂的。

**Comment by jplijplijpli** [comment]
原来log4j的文件扩展名有个typo，是老师专门放的吗：p 

多谢LiuMing同学提醒，改正过来后果然能看到过程：
![image](https://cloud.githubusercontent.com/assets/26088047/24352640/6ba63f1a-1325-11e7-8575-091bb0fa4bc9.png)
