### ISSUE TITLE
[HBase#2 Homework]第8步查看KV值失败

### ISSUE THREAD

**Issue by jplijplijpli** [trex-group/Big-Data#38]
依照Homework的手顺，尝试执行以下命令行
![image](https://cloud.githubusercontent.com/assets/26088047/24579178/26c471c8-172b-11e7-98e5-75222e264148.png)

8的full path如下
![image](https://cloud.githubusercontent.com/assets/26088047/24579220/020bee50-172c-11e7-893c-39f4360eb86a.png)

copy后执行，告诉我file不存在
![image](https://cloud.githubusercontent.com/assets/26088047/24579217/e13c917a-172b-11e7-84f9-f66278b8127f.png)

是否理解题意有误？ 和4月1号么有关系吧。

**Comment by LiuMing5489** [comment]
哈哈。遇到一样的问题了。
我是docker的环境。
把localhost 8020改成master.trex.com:9000解决的。

**Comment by jplijplijpli** [comment]
![image](https://cloud.githubusercontent.com/assets/26088047/24583990/4c5a7762-1798-11e7-91d7-0edf062f43ce.png)

hdfs的location需要参照设定文件
