### ISSUE TITLE
spark1作业第一题启动spark shell好像失败了

### ISSUE THREAD

**Issue by jplijplijpli** [trex-group/Big-Data#43]
![image](https://cloud.githubusercontent.com/assets/26088047/25061314/98535cd2-21ee-11e7-9002-93224a81737f.png)
![image](https://cloud.githubusercontent.com/assets/26088047/25061322/c19bd18c-21ee-11e7-8ed5-cfc7cf975596.png)

报了一堆错，还没有spark context
![image](https://cloud.githubusercontent.com/assets/26088047/25061332/ee29b9ee-21ee-11e7-8c78-f4ad53e091cd.png)

Node好像正常启动了
![image](https://cloud.githubusercontent.com/assets/26088047/25061351/2b6c6ea0-21ef-11e7-8280-6d0d81f042fa.png)

请问有成功的同学吗？

**Comment by jplijplijpli** [comment]
运行spark-submit到好像成功了
![image](https://cloud.githubusercontent.com/assets/26088047/25061452/ee986184-21f1-11e7-90d4-8f035ac5021b.png)
![image](https://cloud.githubusercontent.com/assets/26088047/25061453/f9cb7140-21f1-11e7-9083-4d9a7d9b2a38.png)

**Comment by jplijplijpli** [comment]
指定了master结果也是一样
![image](https://cloud.githubusercontent.com/assets/26088047/25061505/072e73fe-21f3-11e7-8167-0f60f617cd18.png)

**Comment by LiuMing5489** [comment]
记不太清楚了。好像是需要把
Hadoop-NameNode
Hadoop-DateNode-1
Hadoop-DateNode-2
添加到  /etc/hosts 里面

还有就是启动spark-shell之前，需要启动hadoop

**Comment by LiuMing5489** [comment]
嗯，在自己的环境下验证了一下，
不启动hadoop的时候和你的是一样的错误。

**Comment by jplijplijpli** [comment]
原因是：shell模式执行，script里面要求链接hadoop
